### ISSUE TITLE
Automatic Alignment Option

### ISSUE THREAD

**Issue by zcanann** [Squalr/Squalr#157]
I believe standard practice is to assume 1-byte alignment on Byte scans and 2-byte alignment on U/Int16 scans.

This is not being done right now, and we always assume 4-byte alignment by the default settings.

**Comment by zcanann** [comment]
Update: I want to get prefilters and manual scans fast enough that we can always use 1-byte alignment. This may or may not be possible.

Modern games tend to have weird memory constructs nowadays anyways, with bit flags and other things. The alignment optimization that is standard in memory editors tends to do more harm than good.

**Comment by veksha** [comment]
Hello. Maybe this explains why i cannot find some byte values. I think this should be a first priority, it's a show-stopper for me. Thank you for your software it looks very promising!
